apps/UNE/urls.py
from django.urls import path
from apps.UNE.views.une_views import une_view


urlpatterns = [
    path('une/',une_view,name='une_view'),
]

apps/joven_club/urls.py
from django.urls import path
from apps.joven_club.views.jc_views import joven_club_service_view

urlpatterns = [
    path('joven_club/',joven_club_service_view,name='joven_club_view'),
]

apps/salud/urls.py
from django.urls import path
from apps.salud.views.polyclinics_views import polyclinics_view,polyclinics_detail_view
from apps.salud.views.pharmacy_views import pharmacy_view,pharmacy_detail_view
from apps.salud.views.consultingRoom_views import consultingroom_view,consultingroom_detail_view
from apps.salud.views.salud_view import salud_view


urlpatterns = [
    path('salud/',salud_view,name='salud_view'),
    path('polyclinics/',polyclinics_view,name='polyclinics_view'),
    path('polyclinics/<int:pk>',polyclinics_detail_view,name='polyclinics_detail_view'),
    path('pharmacy/',pharmacy_view,name='pharmacy_view'),
    path('pharmacy/<int:pk>',pharmacy_detail_view,name='pharmacy_detail_view'),
    path('consultingroom/',consultingroom_view,name='consultingroom_view'),
    path('consultingroom/<int:pk>',consultingroom_detail_view,name='consultingroom_detail_view'),
]

caonao/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

from .views.home_views import home_view
from .views.fq_views import fq_view
from .views.about_us_views import about_us_view

urlpatterns = [
    path("admin/", admin.site.urls),
    path('appune/',include('apps.UNE.urls')),
    path('appsalud/',include('apps.salud.urls')),
    path('appoficoda/',include('apps.oficoda.urls')),
    path('appinstitution/',include('apps.institucion.urls')),
    path('appestado/',include('apps.estado.urls')),
    path('appeducacion/',include('apps.educacion.urls')),
    path('appcultura/',include('apps.cultura.urls')),
    path('appacueducto/',include('apps.acueducto.urls')),
    path('appjc/',include('apps.joven_club.urls')),
    path('',home_view,name='home_view'),
    path('preguntas_frecuentes/',fq_view,name='fq_view'),
    path('sobre_nosotros/',about_us_view,name='about_us_view'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/UNE/models.py
from django.db import models
from apps.abstract.models import DTA
from utils.validates.validates import validate_letters_numbers_and_spaces
from django.core.validators import MinLengthValidator

# Create your models here.


# Block model
class Block(models.Model):
    """docstring for Block."""
    name = models.CharField('Nombre',validators=[MinLengthValidator(1),validate_letters_numbers_and_spaces], max_length=255, blank=False , null=False, unique=True)
    active = models.BooleanField('Activo', default=True)
    
    class Meta:
        verbose_name= 'Bloque'
        verbose_name_plural= 'Bloques'
        
    def __str__(self) -> str:
        return self.name

# Circuit model
class Circuit(models.Model):
    """docstring for Circuit."""
    name = models.CharField('Nombre',validators=[MinLengthValidator(3),validate_letters_numbers_and_spaces], max_length=255, blank=False , null=False, unique=True)
    block = models.ForeignKey(Block, on_delete=models.CASCADE,verbose_name='Bloque', null=True, blank=True)
    active = models.BooleanField('Activo', default=True)
    
    class Meta:
        verbose_name= 'Circuito'
        verbose_name_plural= 'Circuitos'
        
    def __str__(self) -> str:
        return self.name
    
# Affectation model
class Affectation(DTA):
    """docstring for Affectation."""
    block = models.ForeignKey(Block, on_delete=models.CASCADE,verbose_name='Bloque', null=True, blank=True)
    
    class Meta:
        verbose_name= 'Afectación'
        verbose_name_plural= 'Afectaciones'
        
    def __str__(self) -> str:
        return f'Afectación en el bloque {self.block}'

apps/abstract/models.py
from django.db import models
from utils.validates.validates import validate_digits,validate_letters_numbers_and_spaces,validate_address,validate_text
from django.core.validators import MinLengthValidator


# Create your models here.

# Base abstract model
class Base(models.Model):
    name = models.CharField('Nombre',validators=[MinLengthValidator(3),validate_letters_numbers_and_spaces], max_length=255, blank=False , null=False, unique=True)
    description = models.TextField('Descripción',validators=[MinLengthValidator(3),validate_letters_numbers_and_spaces],max_length=255, blank=False , null=False)
    address = models.CharField('Dirección', max_length=255, validators=[MinLengthValidator(3),validate_address], blank=False , null=False)
    phone = models.CharField('Teléfono',validators=[MinLengthValidator(3),validate_digits],max_length=10, blank=True , null=True )
    active = models.BooleanField('Activo', default=True)
    
    
    """docstring for Base."""
    class Meta:
        abstract = True
        
# Date, Time y Active abstract model
class DTA(models.Model):
    in_date = models.DateField('Fecha inicial',null= False, blank=False)
    in_time = models.TimeField('Hora inicial',null= False, blank=False)
    out_date = models.DateField('Fecha final',null= False, blank=False)
    out_time = models.TimeField('Hora final',null= False, blank=False)
    active = models.BooleanField('Activo', default=True)
    
    
    """docstring for DTA."""
    class Meta:
        abstract = True
        
# ServiceWeekBase abstract model
class WeekBase(models.Model):
    DAYS_OF_WEEK = (
        (0, 'Domingo'),
        (1, 'Lunes'),
        (2, 'Martes'),
        (3, 'Miércoles'),
        (4, 'Jueves'),
        (5, 'Viernes'),
        (6, 'Sábado'),
    )
    in_time = models.TimeField('Hora inicial',null= False, blank=False)
    out_time = models.TimeField('Hora final',null= False, blank=False)
    init_day_of_week = models.IntegerField(
        'Dia inicial del servicio',
        default=0,
        choices=DAYS_OF_WEEK,
        help_text="Selecciona el dia de la semana."
    )
    end_day_of_week = models.IntegerField(
        'Dia final del servicio',
        default=6,
        choices=DAYS_OF_WEEK,
        help_text="Selecciona el dia de la semana."
    )
    
    """docstring for WeekBase."""
    class Meta:
        abstract = True
        
# ServiceWeekBase abstract model
class ServiceWeekBase(models.Model):
    DAYS_OF_WEEK = (
        ('Domingo', 'Domingo'),
        ('Lunes', 'Lunes'),
        ('Martes', 'Martes'),
        ('Miércoles', 'Miércoles'),
        ('Jueves', 'Jueves'),
        ('Viernes', 'Viernes'),
        ('Sábado', 'Sábado'),
    )
    
    name = models.CharField('Nombre',validators=[MinLengthValidator(3),validate_letters_numbers_and_spaces], max_length=255, blank=False , null=False, unique=True)
    description = models.TextField('Descripción',validators=[MinLengthValidator(3),validate_text],max_length=255, blank=False , null=False)
    in_time = models.TimeField('Hora inicial',null= False, blank=False)
    out_time = models.TimeField('Hora final',null= False, blank=False)
    active = models.BooleanField('Activo', default=True)
    init_day_of_week = models.CharField(
        'Dia inicial del servicio',
        default='Domingo',
        choices=DAYS_OF_WEEK,
        max_length=9,
        help_text="Selecciona el dia de la semana."
    )
    end_day_of_week = models.CharField(
        'Dia final del servicio',
        default='Domingo',
        choices=DAYS_OF_WEEK,
        max_length=9,
        help_text="Selecciona el dia de la semana."
    )
    
    """docstring for ServiceWeekBase."""
    class Meta:
        abstract = True
        
    

apps/joven_club/models.py
from django.db import models
from apps.abstract.models import  ServiceWeekBase
# Create your models here.

class JCService(ServiceWeekBase):
    cost = models.DecimalField('Costo', max_digits=10,  decimal_places=2, blank= False, null= False)

    def __str__(self) -> str:
        return f'{self.name}'

apps/salud/models.py
from django.db import models
from apps.abstract.models import Base,  ServiceWeekBase


# Create your models here.

# ConsultingRoom model
class ConsultingRoom(Base):
    """docstring for ConsultingRoom."""
    image = models.ImageField('Imagen',upload_to='consultorio/',null=True,blank=True)
 
    class Meta:
        verbose_name= 'Consultorio'
        verbose_name_plural= 'Consultorios'
        
    def __str__(self) -> str:
        return self.name
    
# ServiceConsultingRoom model
class ServiceConsultingRoom(ServiceWeekBase):
    """docstring for ServiceConsultingRoom."""
    consulting_room = models.ForeignKey(ConsultingRoom, on_delete = models.CASCADE , verbose_name='Consultorio')
    
    
    class Meta:
        verbose_name= 'Servicio de consultorio'
        verbose_name_plural= 'Servicios de consultorios'
        
    def __str__(self) -> str:
        return f'Servicio {self.name} consultorio {self.consulting_room}'
    

    
# Pharmacy model
class Pharmacy(Base):
    """docstring for Pharmacy."""
    image = models.ImageField('Imagen', upload_to='farmacia/',null=True,blank=True)
    
    class Meta:
        verbose_name= 'Farmacia'
        verbose_name_plural= 'Farmacias'
        
    def __str__(self) -> str:
        return self.name
    
    

    
# Polyclinics model
class Polyclinics(Base):
    """docstring for Polyclinics."""
    image = models.ImageField('Imagen', upload_to='policlinico/',null=True,blank=True)
    
    class Meta:
        verbose_name= 'Policlinico'
        verbose_name_plural= 'Policlinicos'
        
    def __str__(self) -> str:
        return self.name
    
# ServicePolyclinics model
class ServicePolyclinics(ServiceWeekBase):
    """docstring for ServicePolyclinics."""
    polyclinics = models.ForeignKey(Polyclinics, on_delete = models.CASCADE , verbose_name='Policlinico')
    
    
    class Meta:
        verbose_name= 'Servicio de policlínico'
        verbose_name_plural= 'Servicios de policlínicos'
        
    def __str__(self) -> str:
        return f'Servicio {self.name} policlínico {self.polyclinics}'
    



# SalePharmacy model
class SalePharmacy(models.Model):
    """docstring for SalePharmacy."""
    DAYS_OF_WEEK = (
        ('Domingo', 'Domingo'),
        ('Lunes', 'Lunes'),
        ('Martes', 'Martes'),
        ('Miércoles', 'Miércoles'),
        ('Jueves', 'Jueves'),
        ('Viernes', 'Viernes'),
        ('Sábado', 'Sábado'),
    )
    
    day_of_week = models.CharField(
        'Dia de venta',
        max_length=10,
        default='Domingo',
        choices=DAYS_OF_WEEK,
        help_text="Selecciona el dia de la semana."
    )
    pharmacy = models.ForeignKey(Pharmacy, on_delete = models.CASCADE , verbose_name='Farmacia')
    consulting_room = models.ForeignKey(ConsultingRoom, on_delete = models.CASCADE , verbose_name='Consultorio')
    
    class Meta:
        verbose_name= 'Venta de medicamentos'
        verbose_name_plural= 'Ventas de medicamentos'
        
    def __str__(self) -> str:
        return f'Venta el {self.day_of_week} por la farmacia {self.pharmacy} al consultorio {self.consulting_room}'
    

apps/UNE/views/une_views.py
from django.shortcuts import render
from apps.UNE.models import Affectation, Block, Circuit


# Create View UNE Table
def une_view(request):
    blocks = Block.objects.filter(active= True)
    affectation= Affectation.objects.filter(
        active = True
    ).order_by('in_date','in_time')
    block_circuit = []
    for block in blocks:
       block_circuit.append({
           'block': block.name,
           'circuit': Circuit.objects.filter(block=block).exclude(active=False)
       })
    context = {'blocks': block_circuit, 'affectation': affectation}
    return render(request,'une_view.html',context)

apps/acueducto/views/waterPlanning_views.py
from django.shortcuts import render
from apps.acueducto.models import WaterPlanning

# vista para acueducto
def waterPlanning_view(request):
    water = WaterPlanning.objects.filter(active = True).order_by('in_date','in_time')
    return render(request,'waterPlanning_view.html',context={'waters':water})

apps/joven_club/views/jc_views.py
from django.shortcuts import render
from apps.joven_club.models import JCService

def joven_club_service_view(request):
    services = JCService.objects.all()

    context = {
        'services':services
    }
    return render(request,'joven_club_view.html',context)

apps/salud/views/consultingRoom_views.py
from django.shortcuts import render
from apps.salud.models import ConsultingRoom,ServiceConsultingRoom


def consultingroom_view(request):
    consultingroom = ConsultingRoom.objects.filter(active = True)

    context = {
        'consultingroom': consultingroom,
     }
    return render(request,'consultingroom_list_view.html',context)

def consultingroom_detail_view(request,pk):
    consultingroom = ConsultingRoom.objects.filter(
        pk = pk,
        active = True
    ).first()

    services = ServiceConsultingRoom.objects.filter(active=True,consulting_room=pk)
    context = {
    'consultingroom': consultingroom,
    'services': services,
    }

    return render(request,'consultingroom_detail_view.html',context)

apps/salud/views/pharmacy_views.py
from django.shortcuts import render
from apps.salud.models import Pharmacy,SalePharmacy

def pharmacy_view(request):
    pharmacy = Pharmacy.objects.filter(active = True)

    context = {
        'pharmacy': pharmacy,
    }

    return render(request,'pharmacy_view.html',context)

def pharmacy_detail_view(request,pk):
    pharmacy = Pharmacy.objects.filter(
        pk = pk,
        active = True
    ).first()

    salepharmacy = SalePharmacy.objects.filter(pharmacy=pk)

    context = {
        'pharmacy': pharmacy,
        'salepharmacy': salepharmacy,
    }

    return render(request,'pharmacy_detail_view.html',context)

apps/salud/views/polyclinics_views.py
from django.shortcuts import render
from apps.salud.models import Polyclinics,ServicePolyclinics


def polyclinics_view(request):
    polyclinics = Polyclinics.objects.filter(active = True)

    context = {
        'polyclinics': polyclinics,
     }
    return render(request,'polyclinics_list_view.html',context)

def polyclinics_detail_view(request,pk):
    polyclinics = Polyclinics.objects.filter(
        pk = pk,
        active = True
    ).first()

    services = ServicePolyclinics.objects.filter(
         polyclinics = polyclinics,
         active = True
    )
    context = {
    'polyclinics': polyclinics,
    'services': services,
    }

    return render(request,'polyclinics_detail_view.html',context)

apps/salud/views/salud_view.py
from django.shortcuts import render



def salud_view(request):
    return render(request,'salud_view.html')

caonao/views/about_us_views.py
from django.shortcuts import render

# vista para el sobre nosotros
def about_us_view(request):
    return render(request,'about_us_view.html')

caonao/views/fq_views.py
from django.shortcuts import render

# vista para preguntas frecuentes
def fq_view(request):
    return render(request,'fq_view.html')

caonao/views/home_views.py
from django.shortcuts import render

# vista para el home
def home_view(request):
    return render(request,'home_view.html')

caonao/templates/culture_detail_view.html
{% extends 'base.html' %} 

{% block contend %}
<!-- About Start -->
    <div class="container-fluid py-5">
        <div class="container pt-5">
            <div class="row">
                <div class="col-lg-6" style="min-height: 500px;">
                    <div class="position-relative h-100">
                        <img class="position-absolute w-100 h-100" src="{{culture.image.url}}" style="object-fit: cover;">
                    </div>
                </div>
                <div class="col-lg-6 pt-5 pb-lg-5">
                    <div class="about-text bg-white p-4 p-lg-5 my-lg-5">
                        <h1 class="mb-3"> {{culture.name}}</h1>
                        <h4 class="mb-3"> Dirección: {{culture.address}}</h4><br>
                        
                        <span> {{culture.description}}</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- About End -->

    {% if projects %}
    <div class="container-fluid py-5">
        <div class="container pt-5 pb-3">
            <div class="text-center mb-3 pb-3">
                <h1>Servicios</h1>
            </div>
            <div class="row">
                <table class="table table-hover" style="margin-top: 5%; padding: 5px;">
                  <thead>
                    <tr>
                      <th scope="col">Nombre</th>
                      <th scope="col">Fecha</th>
                      <th scope="col">Hora</th>
                      <th scope="col">Descripción</th>
                        
                    </tr>
                  </thead>
                    <tbody>
                      
                       
                            {% for project in projects %}
                            <tr>
                                <td>{{ project.name }}</td>   
                                {% if project.in_date == project.out_date %}
                                    <td>{{ project.in_date }}</td>  
                                {% else %}
                                    <td>{{ project.in_date }} al {{ project.out_date }}</td>  
                                {% endif  %}
                                {% if project.in_time == project.out_time %}
                                    <td>{{ project.in_time }}</td>   
                                {% else %}
                                    <td>{{ project.in_time }}-{{ project.out_time }}</td>   
                                {% endif  %}
                                
                                
                                <td>{{ project.description }}</td>  
                            </tr> 
                            {% endfor %}       
                       
                      
                    </tbody>
                  </table>
              </div>
        </div>
      </div>
      
    {% else %}
    <div class="container-fluid py-5">
        <div class="container pt-5 pb-3">
            <div class="text-center mb-3 pb-3">
                <h1>No contiene servicios disponibles</h1>
            </div>
            
        </div>
      </div>
      
    {% endif  %}

{% endblock %}

caonao/templates/culture_list_view.html
{% extends 'base.html' %} 
{% load static %}

{% block contend %}
     <!-- Packages Start -->
<!-- Packages Start -->
<div class="container-fluid py-5">
    <div class="container pt-5 pb-3">
        <div class="text-center mb-3 pb-3">
            <h1>Instituciones de Cultura</h1>
        </div>
        <div class="row align-items-stretch">
            {% for culture in culture_list %}
            <div class="col-lg-4 col-md-6 mb-4">
                <div class="package-item bg-white h-100 mb-2">
                    <img class="img-fluid" src="{{culture.image.url}}" alt="">
                    <div class="p-4 d-flex flex-column">
                        <div class="mb-3">
                            <small><i class="fa fa-map-marker-alt text-primary mr-2">{{culture.address}}</i></small>
                        </div>
                        <a class="h5 text-decoration-none" href="{% url 'culture_detail_view' pk=culture.pk %}">{{culture.name}}</a>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
<!-- Packages End -->

{% endblock %}

caonao/templates/education_detail_view.html
{% extends 'base.html' %} 

{% block contend %}
<!-- About Start -->
    <div class="container-fluid py-5">
        <div class="container pt-5">
            <div class="row">
                <div class="col-lg-6" style="min-height: 500px;">
                    <div class="position-relative h-100">
                        <img class="position-absolute w-100 h-100" src="{{education.image.url}}" style="object-fit: cover;">
                    </div>
                </div>
                <div class="col-lg-6 pt-5 pb-lg-5">
                    <div class="about-text bg-white p-4 p-lg-5 my-lg-5">
                        <h1 class="mb-3">{{education.name}}</h1>
                        <h4 class="mb-3"> Dirección: {{education.address}}</h4><br>
                        
                        <span> {{education.description}}</span>
                        
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- About End -->
    {% if projects %}
    <div class="container-fluid py-5">
        <div class="container pt-5 pb-3">
            <div class="text-center mb-3 pb-3">
                <h1>Proyectos</h1>
            </div>
            <div class="row">
                <table class="table table-hover" style="margin-top: 5%; padding: 5px;">
                  <thead>
                    <tr>
                      <th scope="col">Nombre</th>
                      <th scope="col">Descripción</th>
                        
                    </tr>
                  </thead>
                    <tbody>
                      
                       
                            {% for project in projects %}
                                <tr>
                                    <td>{{ project.name }}</td>   
                                    <td>{{ project.description }}</td>  
                                </tr> 
                            {% endfor %}       
                       
                      
                    </tbody>
                  </table>
              </div>
        </div>
      </div>
      
    {% else %}
    <div class="container-fluid py-5">
        <div class="container pt-5 pb-3">
            <div class="text-center mb-3 pb-3">
                <h1>No contiene servicios disponibles</h1>
            </div>
            
        </div>
      </div>
      
    {% endif  %}

{% endblock %}

caonao/templates/fq_view.html
{% extends 'base.html' %} 


{% block contend %}
<h2>Estas son las preguntas frecuentes</h2>
{% endblock  %}

caonao/templates/institution_list_view.html
{% extends 'base.html' %} 
{% load static %}

{% block contend %}
     <!-- Packages Start -->
<!-- Packages Start -->
<div class="container-fluid py-5">
    <div class="container pt-5 pb-3">
        
        {% if institutions_type %}
            <div class="text-center mb-3 pb-3">
                <h1>Instituciones</h1>
            </div>
            <div class="row">
                
                {% for type in institutions_type %}
                    <div class="col-lg-4 col-md-6 mb-4">
                        <div class="service-item bg-white text-center mb-2 py-5 px-4">
                            <a href="{% url 'institutions_type_view' type=type.name %}">
                                <i class="fa fa-2x fa-university mx-auto mb-4"></i>
                            </a>
                            <h5 class="text-primary mb-2">{{type.name}}</h5>
                            
                        </div>
                    </div>
                {% endfor %}
    
            </div>
        {% else %}
            <div class="text-center mb-3 pb-3">
                <h1>No existe información disponible</h1>
            </div>
        {% endif %}
            
        
    </div>
</div>

<!-- Packages End -->

{% endblock %}

caonao/templates/oficoda_service_detail_view.html
{% extends 'base.html' %} 

{% block contend %}
<!-- About Start -->
    <div class="container-fluid py-5">
        <div class="container pt-5">
            <div class="row">
                <div class="col-lg-6" style="min-height: 500px;">
                    <div class="position-relative h-100">
                        <img class="position-absolute w-100 h-100" src="{{oficoda_service.image.url}}" style="object-fit: cover;">
                    </div>
                </div>
                <div class="col-lg-6 pt-5 pb-lg-5">
                    <div class="about-text bg-white p-4 p-lg-5 my-lg-5">
                        <h1 class="mb-3"> {{oficoda_service.name}}</h1>
                        <h4 class="mb-3"> Dirección: {{oficoda_service.address}}</h4><br>
                        
                        <span> {{oficoda_service.description}}</span>
                        {% comment %} {% for service in services %}
                        <h5>{{service.name}}</h5><hr>
                        {% endfor %} {% endcomment %}
                    </div>
                </div>
            </div>
        </div>
    </div>

    {% if services %}
    <div class="container-fluid py-5">
        <div class="container pt-5 pb-3">
            <div class="text-center mb-3 pb-3">
                <h1>Servicios</h1>
            </div>
            <div class="row">
                <table class="table table-hover" style="margin-top: 5%; padding: 5px;">
                  <thead>
                    <tr>
                      <th scope="col">Nombre</th>
                      <th scope="col">Horario</th>
                      <th scope="col">Descripción</th>
                        
                    </tr>
                  </thead>
                    <tbody>
                      
                       
                            {% for service in services %}
                            <tr>
                                <td>{{ service.name }}</td>   
                                <td>{{ service.get_init_day_of_week_display}} a {{ service.get_end_day_of_week_display}} de {{ service.in_time }}-{{ service.out_time }}</td>   
                                <td>{{ service.description }}</td>  
                            </tr> 
                            {% endfor %}       
                       
                      
                    </tbody>
                  </table>
              </div>
        </div>
      </div>
      
    {% else %}
    <div class="container-fluid py-5">
        <div class="container pt-5 pb-3">
            <div class="text-center mb-3 pb-3">
                <h1>No contiene servicios disponibles</h1>
            </div>
            
        </div>
      </div>
      
    {% endif  %}

    <!-- About End -->

{% endblock %}

caonao/templates/polyclinics_detail_view.html
{% extends 'base.html' %} 

{% block contend %}
<!-- About Start -->
    <div class="container-fluid py-5">
        <div class="container pt-5">
            <div class="row">
                <div class="col-lg-6" style="min-height: 500px;">
                    <div class="position-relative h-100">
                        <img class="position-absolute w-100 h-100" src="{{polyclinics.image.url}}" style="object-fit: cover;">
                    </div>
                </div>
                <div class="col-lg-6 pt-5 pb-lg-5">
                    <div class="about-text bg-white p-4 p-lg-5 my-lg-5">
                        <h1 class="mb-3"> {{polyclinics.name}}</h1>
                        <h4 class="mb-3"> Dirección: {{polyclinics.address}}</h4><br>
                        
                        <span> {{polyclinics.description}}</span>
                        {% comment %} {% for service in services %}
                        <h5>{{service.name}}</h5><hr>
                        {% endfor %} {% endcomment %}
                    </div>
                </div>
            </div>
        </div>
    </div>

    {% if services %}
    <div class="container-fluid py-5">
        <div class="container pt-5 pb-3">
            <div class="text-center mb-3 pb-3">
                <h1>Servicios</h1>
            </div>
            <div class="row">
                <table class="table table-hover" style="margin-top: 5%; padding: 5px;">
                  <thead>
                    <tr>
                      <th scope="col">Nombre</th>
                      <th scope="col">Horario</th>
                      <th scope="col">Descripción</th>
                        
                    </tr>
                  </thead>
                    <tbody>
                      
                       
                            {% for service in services %}
                            <tr>
                                <td>{{ service.name }}</td>   
                                <td>{{ service.get_init_day_of_week_display}} a {{ service.get_end_day_of_week_display}} de {{ service.in_time }}-{{ service.out_time }}</td>   
                                <td>{{ service.description }}</td>  
                            </tr> 
                            {% endfor %}       
                       
                      
                    </tbody>
                  </table>
              </div>
        </div>
      </div>
      
    {% else %}
    <div class="container-fluid py-5">
        <div class="container pt-5 pb-3">
            <div class="text-center mb-3 pb-3">
                <h1>No contiene servicios disponibles</h1>
            </div>
            
        </div>
      </div>
      
    {% endif  %}

    <!-- About End -->

{% endblock %}